import { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowLeft, ArrowUpRight, Check, Menu, X } from 'lucide-react';
import { Button } from '../components/Button';
import { Logo } from '../components/Logo';
import { BOOKING_URL, contact, hotelImages } from '../data/hotel';
import { rooms } from '../data/content';

const pages = {
  '/quartos': { label:'01 — QUARTOS & TARIFAS', title:<>Escolha o seu<br/><i>ritmo.</i></>, lead:'Quartos para diferentes formas de chegar e ficar em Santarém.', image:'/images/room-double-b.png', kind:'rooms' },
  '/eventos': { label:'02 — SALAS & EVENTOS', title:<>Ideias que<br/><i>ganham espaço.</i></>, lead:'Duas salas para reuniões e eventos: Sala Tejo e Sala Alfageme.', image:'/images/event-boardroom.png', kind:'events' },
  '/bar-restaurante': { label:'03 — BAR & RESTAURANTE', title:<>Pausa para<br/><i>saborear.</i></>, lead:'Um momento de pausa dentro da sua estadia no Hotel UMU.', image:hotelImages.breakfast, kind:'bar' },
  '/comodidades': { label:'04 — COMODIDADES', title:<>Tudo o que<br/><i>importa.</i></>, lead:'Os detalhes práticos para uma estadia mais confortável.', image:hotelImages.intro[0], kind:'amenities' },
} as const;
type PageKey=keyof typeof pages;
const amenityList=['Receção 24 horas','TV cabo em todos os quartos','Pequeno-almoço buffet americano','Serviço de quartos','Lavandaria','Cofre','Wi-Fi','Limpeza diária','Elevador','Quartos para não fumadores','Comodidades para pessoas com mobilidade condicionada','Ar-condicionado','Bar','Sala de TV'];

const detailNav=[['Quartos','/quartos'],['Eventos','/eventos'],['Bar & Restaurante','/bar-restaurante'],['Comodidades','/comodidades']];
function Header(){const [open,setOpen]=useState(false);useEffect(()=>{document.body.classList.toggle('menu-open',open);const close=(event:KeyboardEvent)=>event.key==='Escape'&&setOpen(false);window.addEventListener('keydown',close);return()=>{document.body.classList.remove('menu-open');window.removeEventListener('keydown',close)}},[open]);return <><header className="detail-nav"><Logo dark/><nav aria-label="Navegação principal">{detailNav.map(([label,href])=><a href={href} key={href}>{label}</a>)}</nav><a className="nav-book dark-book" href={BOOKING_URL} target="_blank" rel="noreferrer">Reservar <ArrowUpRight size={15}/></a><button className="menu" onClick={()=>setOpen(true)} aria-label="Abrir menu" aria-expanded={open} aria-controls="detail-mobile-navigation"><Menu/></button></header><AnimatePresence>{open&&<motion.div id="detail-mobile-navigation" className="mobile-menu" role="dialog" aria-modal="true" aria-label="Menu de navegação" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div><Logo dark/><button className="menu" onClick={()=>setOpen(false)} aria-label="Fechar menu"><X/></button></div><nav>{detailNav.map(([label,href],index)=><motion.a initial={{opacity:0,x:-20}} animate={{opacity:1,x:0}} transition={{delay:index*.08}} href={href} onClick={()=>setOpen(false)} key={href}>{label}<ArrowUpRight/></motion.a>)}<Button href={BOOKING_URL}>Reservar estadia</Button></nav></motion.div>}</AnimatePresence></>}
function Footer(){return <footer><Logo/><div><p>{contact.address}</p><p><a href={`tel:+351${contact.phone.replaceAll(' ','')}`}>{contact.phone}</a> · <a href={`mailto:${contact.email}`}>{contact.email}</a></p></div><nav><a href="/quartos">Quartos</a><a href="/eventos">Eventos</a><a href="/bar-restaurante">Bar & Restaurante</a><a href="/comodidades">Comodidades</a><a href={BOOKING_URL}>Reservar</a></nav><small>© Hotel UMU · {contact.rnet} · Política de Privacidade · Cookies · Termos/Condições</small></footer>}
export function DetailPage(){const key=window.location.pathname as PageKey; const page=pages[key] ?? pages['/quartos']; return <><Header/><main className="detail"><section className="detail-hero"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.7}}><a className="back" href="/"><ArrowLeft size={15}/> Voltar ao Hotel UMU</a><p className="eyebrow">{page.label}</p><h1>{page.title}</h1><p>{page.lead}</p><Button href={BOOKING_URL}>Reservar estadia</Button></motion.div><img src={page.image} alt="Hotel UMU"/></section>{page.kind==='rooms'&&<RoomsPage/>}{page.kind==='events'&&<EventsPage/>}{page.kind==='bar'&&<BarPage/>}{page.kind==='amenities'&&<AmenitiesPage/>}<section className="detail-cta"><p className="eyebrow">HOTEL UMU · SANTARÉM</p><h2>A sua estadia,<br/><i>ao seu ritmo.</i></h2><Button href={BOOKING_URL}>Ver disponibilidade</Button></section></main><Footer/></>}
function OfficialPhotoStrip(){return <section className="official-strip" aria-label="Fotografias oficiais do Hotel UMU"><img src={hotelImages.editorial[0]} alt="Ambiente do Hotel UMU" loading="lazy"/><img src={hotelImages.editorial[1]} alt="Detalhe do Hotel UMU" loading="lazy"/><img src={hotelImages.editorial[2]} alt="Espaço do Hotel UMU" loading="lazy"/></section>}
function RoomsPage(){return <><section className="detail-section"><div className="detail-heading"><p className="eyebrow">TARIFAS INDICATIVAS</p><h2>O espaço certo<br/><i>para a sua viagem.</i></h2><p>Preços médios e indicativos, sujeitos a alteração sem aviso prévio, conforme ocupação e temporada.</p></div><div className="tariff-grid">{rooms.map(([name,kind,price,image])=><article key={name}><img src={image} alt={name} loading="lazy"/><div><span>{kind}</span><h3>{name}</h3><b>{price}</b><a href={BOOKING_URL}>Reservar <ArrowUpRight size={14}/></a></div></article>)}</div></section><OfficialPhotoStrip/></>}
function EventsPage(){return <><section className="detail-section event-section"><div className="detail-heading"><p className="eyebrow">SALAS & EVENTOS</p><h2>Um encontro<br/><i>com espaço.</i></h2><p>O Hotel UMU apresenta a Sala Tejo e a Sala Alfageme. Para saber mais sobre disponibilidade e configuração, fale diretamente com a equipa.</p><Button secondary href={`mailto:${contact.email}?subject=Pedido%20de%20informa%C3%A7%C3%A3o%20sobre%20salas%20e%20eventos`}>Pedir informação</Button></div><div className="event-cards"><article><img src="/images/event-theatre.png" alt="Sala preparada para evento"/><h3>Sala Tejo</h3></article><article><img src="/images/event-boardroom.png" alt="Sala preparada para reunião"/><h3>Sala Alfageme</h3></article></div></section><OfficialPhotoStrip/></>}
function BarPage(){return <section className="detail-section bar-section"><img src={hotelImages.breakfast} alt="Espaço de hospitalidade do Hotel UMU" loading="lazy"/><div><p className="eyebrow">BAR & RESTAURANTE</p><h2>Um intervalo<br/><i>bem servido.</i></h2><p>O Hotel UMU dispõe de bar e de pequeno-almoço buffet. O pequeno-almoço é servido das 07:30 às 10:00 nos dias úteis e das 08:00 às 11:00 aos fins de semana e feriados.</p><p>Para uma opção mais reservada, há pequeno-almoço no quarto mediante room service.</p><a className="text-link dark-link" href={BOOKING_URL}>Reservar a estadia <ArrowUpRight size={15}/></a></div></section>}
function AmenitiesPage(){return <section className="detail-section"><div className="detail-heading"><p className="eyebrow">COMODIDADES</p><h2>Conforto em<br/><i>cada detalhe.</i></h2><p>Informação oficial do Hotel UMU, pensada para tornar a sua estadia simples e confortável.</p></div><div className="amenity-grid">{amenityList.map((item,i)=><motion.div initial={{opacity:0,y:12}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:(i%3)*.06}} key={item}><Check size={17}/><span>{item}</span></motion.div>)}</div></section>}
