import { useEffect, useState } from 'react';
import { motion, useScroll, AnimatePresence } from 'framer-motion';
import { Menu, X, ArrowDown, ChevronRight, MapPin, Phone, Mail, CalendarDays, Users, Play, Star } from 'lucide-react';
import { Logo } from './components/Logo';
import { Button } from './components/Button';
import { BOOKING_URL, contact, hotelImages } from './data/hotel';
import { rooms, services, reviews } from './data/content';
import { DetailPage } from './pages/DetailPage';

const nav = [['Quartos','/quartos'],['Serviços','#servicos'],['Eventos','/eventos'],['Bar & Restaurante','/bar-restaurante'],['Comodidades','/comodidades']];
const reveal = { initial:{opacity:0,y:28}, whileInView:{opacity:1,y:0}, viewport:{once:true,amount:.18}, transition:{duration:.75} };

function Navbar(){ const {scrollY}=useScroll(); const [solid,setSolid]=useState(false); const [open,setOpen]=useState(false); useEffect(()=>scrollY.on('change',v=>setSolid(v>70)),[scrollY]); useEffect(()=>{document.body.classList.toggle('menu-open',open);const close=(event:KeyboardEvent)=>event.key==='Escape'&&setOpen(false);window.addEventListener('keydown',close);return()=>{document.body.classList.remove('menu-open');window.removeEventListener('keydown',close)}},[open]); return <>
  <header className={`nav ${solid?'solid':''}`}><Logo dark={solid}/><nav aria-label="Navegação principal">{nav.map(([n,h])=><a href={h} key={n}>{n}</a>)}</nav><a className="nav-book" href={BOOKING_URL}>Reservar <ChevronRight size={16}/></a><button className="menu" onClick={()=>setOpen(true)} aria-label="Abrir menu" aria-expanded={open} aria-controls="mobile-navigation"><Menu/></button></header>
  <AnimatePresence>{open&&<motion.div id="mobile-navigation" className="mobile-menu" role="dialog" aria-modal="true" aria-label="Menu de navegação" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div><Logo dark/><button className="menu" onClick={()=>setOpen(false)} aria-label="Fechar menu"><X/></button></div><nav>{nav.map(([n,h],i)=><motion.a initial={{opacity:0,x:-20}} animate={{opacity:1,x:0}} transition={{delay:.08*i}} href={h} onClick={()=>setOpen(false)} key={n}>{n}<ChevronRight/></motion.a>)}<Button href={BOOKING_URL}>Reservar estadia</Button></nav></motion.div>}</AnimatePresence>
</> }

function Booking(){return <section id="reservar" className="booking"><div className="booking-field"><CalendarDays/><span><small>CHECK-IN</small><b>Selecionar data</b></span></div><div className="booking-field"><CalendarDays/><span><small>CHECK-OUT</small><b>Selecionar data</b></span></div><div className="booking-field"><Users/><span><small>HÓSPEDES</small><b>2 hóspedes</b></span></div><a href={BOOKING_URL} className="booking-button">Ver disponibilidade <ChevronRight size={18}/></a></section>}

function Rooms(){const [chosen,setChosen]=useState<number|null>(null); return <section id="quartos" className="rooms section"><motion.div {...reveal} className="section-top"><p className="eyebrow">01 — QUARTOS</p><div><h2>Escolha<br/><i>o seu espaço.</i></h2><p>Conforto pensado para diferentes formas de viajar.</p></div></motion.div><div className="room-track">{rooms.map(([name,kind,price,image],i)=><motion.article {...reveal} transition={{delay:i*.08}} className="room-card" key={name}><div className="room-image"><img src={image} alt={`${name}, Hotel UMU`} loading="lazy"/><span>{kind}</span></div><div className="room-info"><div><h3>{name}</h3><p>{price}</p></div><button onClick={()=>setChosen(i)} aria-label={`Ver ${name}`}><ChevronRight/></button></div></motion.article>)}</div><p className="price-note">Valores indicativos, sujeitos a disponibilidade, ocupação e temporada.</p><AnimatePresence>{chosen!==null&&<motion.div className="modal-bg" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setChosen(null)}><motion.div className="room-modal" initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} exit={{y:30,opacity:0}} onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setChosen(null)}><X/></button><img src={rooms[chosen][3]} alt=""/><p className="eyebrow">{rooms[chosen][1]}</p><h2>{rooms[chosen][0]}</h2><p>{rooms[chosen][2]}</p><p>Informações e condições confirmadas no processo de reserva.</p><Button>Reservar este quarto</Button></motion.div></motion.div>}</AnimatePresence></section>}

function Services(){return <section id="servicos" className="services"><div className="service-title"><span>02 — SERVIÇOS</span><h2>SERV<br/>ICES</h2></div><div className="service-composition" aria-hidden="true"><span>ESTADIA</span><i/></div><div className="service-intro"><p>Para que a estadia seja simples, confortável e inteiramente sua.</p><span className="red-dot"/></div><div className="service-list">{services.map(([n,title,text])=><motion.article {...reveal} key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div><ChevronRight/></motion.article>)}</div></section>}

function Reviews(){return <section className="reviews section"><motion.div {...reveal} className="review-heading"><p className="eyebrow">05 — OPINIÕES</p><h2>Ouvido por<br/><i>quem ficou.</i></h2><div className="score"><b>3,7</b><span>/ 5<br/><small>1.097 avaliações · Google</small></span></div></motion.div><div className="review-track">{reviews.map(([quote,name,source])=><motion.figure {...reveal} key={name}><Star className="star" fill="currentColor"/><blockquote>{quote}</blockquote><figcaption><b>{name}</b><span>{source}</span></figcaption></motion.figure>)}</div></section>}

function App(){if (window.location.pathname !== '/') return <DetailPage/>; return <><Navbar/><main id="top"><section className="hero"><img src={hotelImages.hero} alt="Quarto do Hotel UMU"/><div className="hero-overlay"/><motion.div className="hero-copy" initial={{opacity:0,y:22}} animate={{opacity:1,y:0}} transition={{duration:1}}><p className="eyebrow">HOTEL UMU <span/> SANTARÉM · PORTUGAL</p><h1>Chegue.<br/><i>Abrande.</i><br/>Descubra.</h1><p className="hero-desc">Conforto, localização e hospitalidade no centro de Santarém.</p><div><Button>Reservar estadia</Button><a className="text-link" href="#intro">Explorar o hotel <ArrowDown size={15}/></a></div></motion.div><a href="#intro" className="scroll-cue">SCROLL PARA DESCOBRIR <span/></a></section><Booking/>
<section id="intro" className="intro section"><motion.div {...reveal} className="intro-copy"><p className="eyebrow">HOTEL UMU · SANTARÉM</p><h2>Um lugar para chegar.<br/><i>Um ponto de partida para descobrir.</i></h2><p>O Hotel UMU está situado no centro de Santarém, oferecendo uma localização prática para quem visita a cidade ou viaja pela região.</p><div className="stats"><b>400M <small>DO ACESSO À A1</small></b><b>RNET 1206 <small>HOTEL UMU</small></b></div></motion.div><motion.div {...reveal} className="intro-photos"><img src={hotelImages.intro[0]} alt="Quarto do Hotel UMU" loading="lazy"/><img src={hotelImages.intro[1]} alt="Detalhe de quarto do Hotel UMU" loading="lazy"/><span>CHEGAR · FICAR · DESCOBRIR</span></motion.div></section>
<Rooms/><Services/>
<section id="santarem" className="city section"><motion.div {...reveal} className="city-photo"><img src={hotelImages.intro[0]} alt="Hotel UMU em Santarém" loading="lazy"/><div>03<br/>SANTARÉM</div></motion.div><motion.div {...reveal} className="city-copy"><p className="eyebrow">A CIDADE À PORTA</p><h2>Santarém começa<br/><i>à porta.</i></h2><p>No centro da cidade e a cerca de 400 metros do acesso à A1, o Hotel UMU é um ponto de partida prático para descobrir Santarém e seguir pela região.</p><a className="text-link dark-link" href="#contactos">Ver localização <ArrowDown size={15}/></a></motion.div></section>
<section id="pequeno-almoco" className="breakfast"><img src={hotelImages.breakfast} alt="Espaço do Hotel UMU" loading="lazy"/><motion.div {...reveal}><p className="eyebrow">04 — HOSPITALIDADE</p><h2>Comece o dia<br/><i>com calma.</i></h2><p>Pequeno-almoço buffet servido na sala de pequenos-almoços. Durante a semana, das <b>07:30 às 10:00</b>; aos fins de semana e feriados, das <b>08:00 às 11:00</b>.</p><p>Também disponível no quarto, mediante room service.</p></motion.div></section>
<Reviews/>
<section id="contactos" className="location section"><motion.div {...reveal}><p className="eyebrow">06 — LOCALIZAÇÃO</p><h2>No centro de<br/><i>Santarém.</i></h2><p className="address"><MapPin/> {contact.address}</p><p className="address"><Phone/> {contact.phone}</p><p className="address"><Mail/> {contact.email}</p><Button secondary href="https://maps.google.com/?q=Hotel+UMU+Santar%C3%A9m">Abrir no Google Maps</Button></motion.div><div className="map"><div className="map-grid"/><div className="pin"><MapPin fill="currentColor"/><b>HOTEL<br/>UMU</b></div><span>400M<br/><small>DO ACESSO À A1</small></span></div></section>
<section className="final"><img src={hotelImages.final} alt="Hotel UMU" loading="lazy"/><div><p className="eyebrow">HOTEL UMU · SANTARÉM</p><h2>A sua próxima<br/><i>estadia começa aqui.</i></h2><Button>Reservar estadia</Button><a className="final-contact" href={`mailto:${contact.email}`}>Contactar o hotel</a></div></section></main><footer><Logo/><div><p>{contact.address}</p><p>{contact.phone} · {contact.email}</p></div><nav>{nav.map(([n,h])=><a href={h} key={n}>{n}</a>)}<a href={BOOKING_URL}>Reservar</a></nav><small>© Hotel UMU · {contact.rnet} · Política de Privacidade · Cookies · Termos/Condições</small></footer><a className="sticky-book" href="#reservar">Reservar <ChevronRight/></a></>}
export default App;
